# Generated by Django 5.0.7 on 2024-10-26 07:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0003_remove_trainingmaterial_training_module_and_more'),
        ('trainingCandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleProgress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_studied', models.BooleanField(default=False)),
                ('studied_at', models.DateTimeField(blank=True, null=True)),
                ('candidate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='module_progresses', to='trainingCandidateApp.candidate')),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='trainingApp.module')),
            ],
            options={
                'unique_together': {('candidate', 'module')},
            },
        ),
    ]
