# Generated by Django 5.0.7 on 2024-10-13 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0002_alter_user_managers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
        migrations.AddField(
            model_name='user',
            name='picture_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceho', 'Health Authority'), ('chw', 'Community Health Worker'), ('patient', 'Patient')], default='patient', max_length=20),
        ),
    ]
