# Generated by Django 5.0.7 on 2024-10-14 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0003_remove_user_username_user_picture_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceho', 'Health Authority'), ('chw', 'Community Health Worker'), ('citizen', 'Citizen')], default='patient', max_length=20),
        ),
    ]
