# Generated by Django 5.0.7 on 2024-10-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userApp', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ceho', 'Health Authority'), ('chw', 'Community Health Worker'), ('citizen', 'Citizen')], default='citizen', max_length=20),
        ),
    ]
