# Generated by Django 5.0.7 on 2024-10-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointmentApp', '0001_initial'),
        ('communityHealthWorkApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='appointed_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appointments_assigned', to='communityHealthWorkApp.communityhealthworker'),
        ),
    ]
