# Generated by Django 4.2.17 on 2025-03-23 07:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('appointmentApp', '0003_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='due_date',
            field=models.DateTimeField(default=datetime.datetime(2025, 3, 30, 7, 51, 21, 807110, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
