# Generated by Django 4.2.17 on 2025-03-23 12:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('serviceApp', '0002_initial'),
        ('appointmentApp', '0004_appointment_due_date_appointment_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='appointments', to='serviceApp.service'),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='address',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='details',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='due_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='first_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='last_name',
            field=models.CharField(max_length=50),
        ),
        migrations.AddConstraint(
            model_name='appointment',
            constraint=models.UniqueConstraint(fields=('appointed_to', 'first_name', 'last_name', 'due_date'), name='unique_appointment'),
        ),
    ]
