# Generated by Django 5.0.7 on 2024-10-24 13:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('examApp', '0001_initial'),
        ('examResultApp', '0001_initial'),
        ('trainingCandidateApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='examresult',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='trainingCandidateApp.candidate'),
        ),
        migrations.AddField(
            model_name='examresult',
            name='exam',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='examApp.exam'),
        ),
    ]
