# Generated by Django 5.0.7 on 2024-10-14 15:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('materials', models.FileField(upload_to='trainings/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('ccreated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainigs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
