# Generated by Django 5.0.7 on 2024-10-14 15:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainingApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='training',
            old_name='ccreated_by',
            new_name='created_by',
        ),
    ]
