# Generated by Django 5.0.7 on 2024-10-24 13:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('serviceApp', '0002_initial'),
        ('trainingApp', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trainings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='training',
            name='service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='serviceApp.service'),
        ),
        migrations.AddField(
            model_name='trainingmaterial',
            name='training',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='materials', to='trainingApp.training'),
        ),
        migrations.AlterUniqueTogether(
            name='training',
            unique_together={('name', 'service')},
        ),
    ]
